# shellcheck shell=bash
# ------------------------------- #
# Here Be Aliases (And Functions) #
# ------------------------------- #

# ---------- #
# Ls aliases #
# ---------- #
alias ls='ls --group-directories-first --time-style=+"%Y.%m.%d %H:%M" --color=auto'
alias ll='ls --almost-all -l --classify --human-readable'
alias la='ls --almost-all'
alias l='ls -C --classify'
alias lt='ls --human-readable --size -1 -S --classify'

# ------------ #
# Grep aliases #
# ------------ #
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias hgrep='history | grep'

# ------------------ #
# Navigation aliases #
# ------------------ #
alias ..='cd ../'
alias ...='cd../../'
alias ....='cd../../../'
alias ~='cd ~'

function -() {
  cd - || return ${?}
}

function gitc() {
  git clone "${1}" || return "${?}"
  cd "$(basename "${1}" .git)" || return "${?}"
}

# ----------------- #
# Vim style aliases #
# ----------------- #
alias :q='exit 0'
alias :e='${VISUAL}'

# -------------------- #
# Drop-In Replacements #
# -------------------- #
alias vim='${VISUAL}'
alias vi='{$VISUAL}'
if [[ -f "${REPOSITORY_DIR}/directory-explorer/directory-explorer.sh" ]]; then
  alias cd='de'
fi

# ---------------- #
# Shell Cheatsheet #
# ---------------- #
function cs() {
  curl -s "https://cht.sh/$1?qT&style=bw"
}

# ----------- #
# Easier Open #
# ----------- #
alias open='xdg-open'

# ----------- #
# Quick Edits #
# ----------- #
alias bashrc='$VISUAL ~/.bashrc && source ~/.bashrc'
alias vimrc='$VISUAL ~/.config/nvim/init.lua'

# vim: set filetype=bash:
