# shellcheck shell=bash
# --------------------
# Noninteractive Guard
# --------------------
case $- in
*i*) ;;
*) return ;;
esac

# ------ #
# Shopts #
# ------ #
shopt -s cdspell        # Allows cd to autocorrect typos
shopt -s checkwinsize   # Check the window size after each command and update LINES/COLUMNS
shopt -s cmdhist        # Save multiline commands in history
shopt -s dotglob        # Dotfiles are matched during filename expansion
shopt -s dirspell       # Allows typos when tab completing paths
shopt -s direxpand      # Expands variables into the path they represent
shopt -s expand_aliases # Aliases work as expected
shopt -s histappend     # Append rather than overwriting history
shopt -s hostcomplete   # Attempts hostname completion when @ is present in a string

# ----------- #
# Completions #
# ----------- #
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

# ------- #
# Aliases #
# ------- #
if [ -e "$HOME"/.bash_aliases ]; then
  . "$HOME/.bash_aliases"
fi

# ----------------- #
# Readline bindings #
# ----------------- #
bind "set completion-ignore-case on"     # Case insensitive file completion
bind "set completion-map-case on"        # Hyphens and underscores are equivalent
bind "set show-all-if-ambiguous on"      # Display ambiguous matches on first tab press
bind "set mark-symlinked-directories on" # Autoadd trailing slash when completing directory symlinks
bind "set bell-style none"
bind "set show-mode-in-prompt"
bind "set editing-mode vi"
bind "set vi-ins-mode-string \001\033[1;32m\002[INSERT] \001\033[0m\002"
bind "set vi-cmd-mode-string \001\033[1;33m\002[COMMAND] \001\033[0m\002"

# ----------- #
# PS1 and PS4 #
# ----------- #
PROMPT_DIRTRIM=2

function parseVenv() {
  if [ -n "$venv" ]; then
    echo -e "\001\033[1;34m\002(\001\033[1;36m\002$venv\001\003[1;34m\002) "
  fi
}

PS1='\001\033[1;34m\002[\001\033[1;37m\002\t\001\033[1;34m\002] $(parseVenv)\001\033[0m\002\u\001\033[1;34m\002@\001\033[0m\002\h\n\001\033[1;37m\002\w\001\033[0m\002 '

PS4='+${BASH_SOURCE[0]##*/}($LINENO)/${FUNCNAME[0]}> '

# ------------------ #
# Navigation Helpers #
# ------------------ #
if [ -f "$HOME/repositories/directory-explorer/directory-explorer.sh" ]; then
  . "$HOME/repositories/directory-explorer/directory-explorer.sh"
fi

# --------- #
# ENV Setup #
# --------- #
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export TMPDIR="/tmp"

export EDITOR="nvim"
export VISUAL="$EDITOR"

export LANG="en_US.UTF-8"
export RANGER_LOAD_DEFAULT_RC="FALSE"

# --------------------------------- #
# User-Made Executables and Scripts #
# --------------------------------- #
if [ -d "$HOME/bin" ]; then
  export PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
  export PATH="$HOME/.local/bin:$PATH"
fi

# --------------------- #
# History Configuration #
# --------------------- #
export HISTCONTROL=ignoreboth # Ignore empty & duplicate content
export HISTSIZE=1000
export HISTFILESIZE=${HISTSIZE}
export HISTTIMEFORMAT="[%Y-%m-%d %T] " # Change date format to YYYY-mm-dd
export HISTIGNORE="&:ls:ll:la:l:lt:pwd:exit:\:e\:q:history:grep"

# vim: set filetype=bash:
