# shellcheck shell=bash
# ------------------------------- #
# Here Be Aliases (And Functions) #
# ------------------------------- #

# ---------- #
# Ls aliases #
# ---------- #
alias ls='ls --group-directories-first --time-style=+"%Y.%m.%d %H:%M" --color=auto'
alias ll='ls --almost-all -l --classify --human-readable'
alias la='ls --almost-all'
alias l='ls -C --classify'
alias lt='ls --human-readable --size -1 -S --classify'

# ------------ #
# Grep aliases #
# ------------ #
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias hgrep='history | grep'

# ------------------ #
# Navigation aliases #
# ------------------ #
alias ..='cd ../'
alias ...='cd../../'
alias ....='cd../../../'
alias ~='cd ~'

function -() {
  cd - || return ${?}
}

# ----------- #
# Git Aliases #
# ----------- #
alias gs='git status'         # [G]it [S]tatus
alias gd='git diff ':!*lock'' # [G]it [D]iff
alias gdf='git diff'          # [G]it [D]iff [F]ull
alias gco='git checkout'      # [G]it [C]heck[o]ut

# ------------------------------- #
#      [G]it [M]ain [B]ranch      #
# Get the name of the main branch #
# ------------------------------- #
function gmb() {
  local main
  main=$(git symbolic-ref --short refs/remotes/origin/HEAD)
  status="${?}"
  main=${main#origin/}
  [[ -n ${main} ]] || return "${status}"
  printf "%s\n" "${main}"
}

# -------------------------------------------------------------------------- #
#                            [G]it [N]ew [B]ranch                            #
# Create a new branch, using $USER-Year-Month-Day if no template is provided #
# -------------------------------------------------------------------------- #
function gnb() {
  local branchname
  branchname="${1:-$(printf "%s-%(%Y-%m-%d)T" "${USER}" -1)}"
  git checkout -b "${branchname}"
}
# ------------------------------------- #
#   [G]it [R]epository [C]lone and CD   #
# Clone a git repository and CD into it #
# ------------------------------------- #
function grc() {
  git clone "${1}" || return "${?}"
  cd "$(basename "${1}" .git)" || return "${?}"
}

# ----------------- #
# Vim style aliases #
# ----------------- #
alias :q='exit 0'
alias :e='${VISUAL}'

# -------------------- #
# Drop-In Replacements #
# -------------------- #
alias vim='${VISUAL}'
alias vi='${VISUAL}'
if [[ -f "${REPOSITORY_DIR}/directory-explorer/directory-explorer.sh" ]]; then
  alias cd='de'
fi

# ---------------- #
# Shell Cheatsheet #
# ---------------- #
function cs() {
  curl -s "https://cht.sh/$1?qT&style=bw"
}

# ----------- #
# Easier Open #
# ----------- #
if xdg-open --version &>/dev/null; then
  alias open='xdg-open'
fi

# ----------- #
# Quick Edits #
# ----------- #
alias bashrc='$VISUAL ~/.bashrc && source ~/.bashrc'
alias vimrc='$VISUAL ~/.config/nvim/init.lua'

# vim: set filetype=bash:
