# shellcheck shell=bash
# -------------------- #
# Noninteractive Guard #
# -------------------- #
case $- in
*i*) ;;
*) return ;;
esac

# ------ #
# Shopts #
# ------ #
shopt -s cdspell        # Allows cd to autocorrect typos
shopt -s checkwinsize   # Check the window size after each command and update LINES/COLUMNS
shopt -s cmdhist        # Save multiline commands in history
shopt -s dotglob        # Dotfiles are matched during filename expansion
shopt -s dirspell       # Allows typos when tab completing paths
shopt -s direxpand      # Expands variables into the path they represent
shopt -s expand_aliases # Aliases work as expected
shopt -s histappend     # Append rather than overwriting history
shopt -s hostcomplete   # Attempts hostname completion when @ is present in a string

# ----------- #
# Completions #
# ----------- #
if [[ -f /etc/bash_completion ]]; then
  . /etc/bash_completion 2>/dev/null
elif [[ -f ~/.bash_completion ]]; then
  . ~/.bash_completion 2>/dev/null
fi

# ----------------- #
# Readline bindings #
# ----------------- #
bind "set completion-ignore-case on"     # Case insensitive file completion
bind "set completion-map-case on"        # Hyphens and underscores are equivalent
bind "set show-all-if-ambiguous on"      # Display ambiguous matches on first tab press
bind "set mark-symlinked-directories on" # Autoadd trailing slash when completing directory symlinks
bind "set bell-style none"
bind "set show-mode-in-prompt"
bind "set editing-mode vi"
bind "set vi-ins-mode-string \001\033[1;32m\002[INSERT] \001\033[0m\002"
bind "set vi-cmd-mode-string \001\033[1;33m\002[COMMAND] \001\033[0m\002"
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

# ----------- #
# PS1 and PS4 #
# ----------- #
PROMPT_DIRTRIM=2

function parseVenv() {
  if [[ -n "${venv}" ]]; then
    echo -e "\001\033[1;34m\002(\001\033[1;36m\002${venv}\001\033[1;34m\002) "
  fi
}

function parseMambaEnv() {
  if [[ -n "${CONDA_DEFAULT_ENV}" ]]; then
    echo -e "\001\033[1;34m\002(\001\033[1;36m\002${CONDA_DEFAULT_ENV}\001\033[1;34m\002) "
  fi
}

PS1='\001\033[1;34m\002[\001\033[1;37m\002\t\001\033[1;34m\002] $(parseVenv)$(parseMambaEnv)\001\033[0m\002\u\001\033[1;34m\002@\001\033[0m\002\h\n\001\033[1;37m\002\w\001\033[0m\002 '

PS4='+${BASH_SOURCE[0]##*/}($LINENO)/${FUNCNAME[0]}> '

# --------- #
# ENV Setup #
# --------- #
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_DOCUMENTS_DIR="${HOME}/Documents"

export TMPDIR="/tmp"

if nvim --version >/dev/null 2>&1; then
  export EDITOR="nvim"
elif vim --version >/dev/null 2>&1; then
  export EDITOR="vim"
elif vi --version >/dev/null 2>&1; then
  export EDITOR="vi"
elif nano --version >/dev/null 2>&1; then
  export EDITOR="nano"
else
  echo "WARNING: EDITOR could not be set." >&2
fi
if [[ -n "${EDITOR}" ]]; then
  export VISUAL="${EDITOR}"
fi

export LANG="en_US.UTF-8"

# Exports a singleton repository directory, using my common paths
declare -a repository_directories
repository_directories=("${HOME}/repositories" "${XDG_DOCUMENTS_DIR}/repositories")
for path in "${repository_directories[@]}"; do
  [[ -d "${path}" ]] && export REPOSITORY_DIR="${path}" && break
done

export MAMBA_EXE="${HOME}/.src/miniforge3/bin/mamba"
export MAMBA_ROOT_PREFIX="${HOME}/.src/miniforge3"

# ------------------ #
# Navigation Helpers #
# ------------------ #
if [[ -f "${REPOSITORY_DIR}/directory-explorer/directory-explorer.sh" ]]; then
  . "${REPOSITORY_DIR}/directory-explorer/directory-explorer.sh"
fi

# ------- #
# Aliases #
# ------- #
if [[ -e "${HOME}"/.bash_aliases ]]; then
  . "${HOME}/.bash_aliases" 2>/dev/null
fi

# ----- #
# Mamba #
# ----- #
if [[ -f "${MAMBA_EXE}" ]]; then
  if __mamba_setup="$("${MAMBA_EXE}" shell hook --shell bash --root-prefix "${MAMBA_ROOT_PREFIX}" 2>/dev/null)"; then
    eval "${__mamba_setup}"
  else
    alias mamba='${MAMBA_EXE}'
  fi
  unset __mamba_setup
fi

# ----- #
# Pyenv #
# ----- #

export PYENV_ROOT="${HOME}/.src/pyenv"
[[ -d ${PYENV_ROOT}/bin ]] && export PATH="${PYENV_ROOT}/bin:$PATH" && eval "$(pyenv init - bash)"

# --------------------------------- #
# User-Made Executables and Scripts #
# --------------------------------- #
# Extends $PATH with all of my common places for self-made executables
declare -a user_executable_paths
user_executable_paths=("${HOME}/bin" "${HOME}/.bin" "${HOME}/.local/bin")
for path in "${user_executable_paths[@]}"; do
  [[ -d "${path}" ]] && export PATH="${path}:${PATH}"
done

# --------------------- #
# History Configuration #
# --------------------- #
export HISTCONTROL=ignoreboth # Ignore empty & duplicate content
export HISTSIZE=1000
export HISTFILESIZE=${HISTSIZE}
export HISTTIMEFORMAT="[%Y-%m-%d %T] " # Change date format to YYYY-mm-dd
export HISTIGNORE="&:ls:ll:la:l:lt:pwd:exit:\:e\:q:history:grep"

# vim: set filetype=bash:
