# shellcheck shell=bash
# --------- #
# ENV Setup #
# --------- #

# ----------------- #
# XDG Configuration #
# ----------------- #
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_DOCUMENTS_DIR="${HOME}/Documents"

# -------------------- #
# Editor Configuration #
# -------------------- #
if nvim --version >/dev/null 2>&1; then
  export EDITOR="nvim"
elif vim --version >/dev/null 2>&1; then
  export EDITOR="vim"
elif vi --version >/dev/null 2>&1; then
  export EDITOR="vi"
elif nano --version >/dev/null 2>&1; then
  export EDITOR="nano"
else
  printf "WARNING: EDITOR could not be set.\n" >&2
fi
if [[ -n "${EDITOR}" ]]; then
  export VISUAL="${EDITOR}"
fi

# --------------------- #
# History Configuration #
# --------------------- #
export HISTCONTROL=ignoreboth # Ignore empty & duplicate content
export HISTSIZE=1000
export HISTFILESIZE=${HISTSIZE}
export HISTTIMEFORMAT="[%Y-%m-%d %T] " # Change date format to YYYY-mm-dd
export HISTIGNORE="&:ls:ll:la:l:lt:pwd:exit:\:e\:q:history:grep"

# ------------------- #
# Misc Configurations #
# ------------------- #
export LANG="en_US.UTF-8"
export TMPDIR="/tmp"

# ------------------------- #
# Safe Path Insert Function #
# ------------------------- #
function _path_insert() {
  case ":${PATH:=${1}}:" in
  *:"${1}":*) ;;
  *)
    export PATH="${1}:${PATH}"
    ;;
  esac
}

# ----------------------------- #
# Python Environment Management #
# ----------------------------- #
[[ -f "${HOME}/.src/miniforge3/bin/mamba" ]] && export MAMBA_EXE="${HOME}/.src/miniforge3/bin/mamba"
[[ -d "${HOME}/.src/miniforge3" ]] && export MAMBA_ROOT_PREFIX="${HOME}/.src/miniforge3"
if [[ -f "${MAMBA_EXE}" ]]; then
  if __mamba_setup="$("${MAMBA_EXE}" shell hook --shell bash --root-prefix "${MAMBA_ROOT_PREFIX}" 2>/dev/null)"; then
    eval "${__mamba_setup}"
  else
    alias mamba='${MAMBA_EXE}'
  fi
  unset __mamba_setup
fi

[[ -d "${HOME}/.src/pyenv" ]] && export PYENV_ROOT="${HOME}/.src/pyenv"
[[ -d "${PYENV_ROOT}/bin" ]] && _path_insert "${PYENV_ROOT}/bin" && eval "$(pyenv init - bash)"

# --------------------------------- #
# User-Made Executables and Scripts #
# --------------------------------- #
declare -a user_executable_paths
user_executable_paths=("${HOME}/bin" "${HOME}/.bin" "${HOME}/.local/bin")
for path in "${user_executable_paths[@]}"; do
  [[ -d "${path}" ]] && _path_insert "${path}"
done

# --------------------------------------- #
# Export a Singleton Repository Directory #
# --------------------------------------- #
declare -a repository_directories
repository_directories=("${HOME}/repositories" "${XDG_DOCUMENTS_DIR}/repositories")
for path in "${repository_directories[@]}"; do
  [[ -d "${path}" ]] && export REPOSITORY_DIR="${path}" && break
done

unset -f _path_insert

# -------------------- #
# Noninteractive Guard #
# -------------------- #
case $- in
*i*) ;;
*) return ;;
esac

# ------ #
# Shopts #
# ------ #
shopt -s cdspell        # Allows cd to autocorrect typos
shopt -s checkwinsize   # Check the window size after each command and update LINES/COLUMNS
shopt -s cmdhist        # Save multiline commands in history
shopt -s dotglob        # Dotfiles are matched during filename expansion
shopt -s dirspell       # Allows typos when tab completing paths
shopt -s direxpand      # Expands variables into the path they represent
shopt -s expand_aliases # Aliases work as expected
shopt -s histappend     # Append rather than overwriting history
shopt -s hostcomplete   # Attempts hostname completion when @ is present in a string

# ----------- #
# Completions #
# ----------- #
if [[ -f /etc/bash_completion ]]; then
  . /etc/bash_completion 2>/dev/null
elif [[ -f ~/.bash_completion ]]; then
  . ~/.bash_completion 2>/dev/null
fi

# ----------------- #
# Readline bindings #
# ----------------- #
bind "set completion-ignore-case on"     # Case insensitive file completion
bind "set completion-map-case on"        # Hyphens and underscores are equivalent
bind "set show-all-if-ambiguous on"      # Display ambiguous matches on first tab press
bind "set mark-symlinked-directories on" # Autoadd trailing slash when completing directory symlinks
bind "set bell-style none"
bind "set show-mode-in-prompt"
bind "set editing-mode vi"
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

# ----------- #
# PS1 and PS4 #
# ----------- #
PROMPT_DIRTRIM=2

_blue_bold='\001\033[1;34m\002'
_bright_blue_bold='\001\033[1;94m\002'
_gray_bold='\001\033[1;90m\002'
_green_bold='\001\033[1;32m\002'
_cyan_bold='\001\033[1;36m\002'
_red_bold='\001\033[1;31m\002'
_white_bold='\001\033[1;37m\002'
_yellow_bold='\001\033[1;33m\002'
_reset='\001\033[0m\002'

function returnCode() {
  status="${?}"
  columns=$(($(tput cols) + 27))
  status_string=$(printf "%b(%b%s%b)" "${_blue_bold}" "${_cyan_bold}" "${status}" "${_blue_bold}")
  printf "%*s\r" "${columns}" "${status_string}"
}

function timestamp() {
  printf "%b[%b%(%H:%M:%S)T%b] " "${_blue_bold}" "${_white_bold}" -1 "${_blue_bold}"
}

function parseVenv() {
  if [[ -n "${venv}" ]]; then
    printf "%b(%b%s%b) " "${_blue_bold}" "${_cyan_bold}" "${venv}" "${_blue_bold}"
  fi
}

function parseMambaEnv() {
  if [[ -n "${CONDA_DEFAULT_ENV}" ]]; then
    printf "%b(%b%s%b) " "${_blue_bold}" "${_cyan_bold}" "${CONDA_DEFAULT_ENV}" "${_blue_bold}"
  fi
}

function parseUser() {
  if [[ "${EUID}" -eq 0 ]]; then
    prompt_color="${_red_bold}"
  else
    prompt_color="${_reset}"
  fi
  printf "%b%s" "${prompt_color}" "${USER}"
}

function parseHost() {
  if [[ -n "${SSH_CONNECTION}" ]]; then
    printf "%b[%bssh%b] %b@ %b%s" "${_gray_bold}" "${_bright_blue_bold}" "${_gray_bold}" "${_blue_bold}" "${_reset}" "${HOSTNAME%%.*}"
  fi
}

bind "set vi-ins-mode-string ${_gray_bold}[${_green_bold}INSERT${_gray_bold}]"
bind "set vi-cmd-mode-string ${_gray_bold}[${_yellow_bold}COMMAND${_gray_bold}]"
PS1="\$(returnCode)"
PS1+="\$(timestamp)"
PS1+="\$(parseVenv)"
PS1+="\$(parseMambaEnv)"
PS1+="\$(parseUser)"
PS1+="\$(parseHost)"
PS1+="\n ${_white_bold}\w${_reset} "

PS4='+${BASH_SOURCE[0]##*/}($LINENO)/${FUNCNAME[0]}> '

# ------- #
# Aliases #
# ------- #
if [[ -e "${HOME}"/.bash_aliases ]]; then
  . "${HOME}/.bash_aliases" 2>/dev/null
fi

# vim: set filetype=bash:
