set nocompatible            " Use Vim defaults instead of old Vi behavior

" ---------------- "
" Plugin Bootstrap "
" ---------------- "
if executable('curl')
	let target_path = expand('~/.vim/colors/gruvbox8.vim')
	if !filereadable(target_path)
		echo "Installing gruvbox colortheme..."
		silent exec "!curl -fLo ~/.vim/colors/gruvbox8.vim --create-dirs https://codeberg.org/lifepillar/vim-gruvbox8/raw/commit/ee054a75163bdfcbbc98c19a9e70ec4ff8af5aee/colors/gruvbox8.vim"
	endif
else
	echoerr "Curl is required to bootstrap colorscheme"
	execute "q!"
endif
if executable('git')
	" Git Gutter
	let target_path = expand('~/.vim/pack/airblade/start/vim-gitgutter')
	if ! isdirectory(target_path)
		echo "Installing vim-gitgutter..."
		silent exec "!git clone --depth 1 https://github.com/airblade/vim-gitgutter.git "target_path
	endif
	" Flash Yank Text
	let target_path = expand('~/.vim/pack/statox/start/FYT.vim')
	if !isdirectory(target_path)
		echo "Installing FYT..."
		silent exec "!git clone --depth 1 https://github.com/statox/FYT.vim.git "target_path
	endif
	" ALE
	let target_path = expand('~/.vim/pack/dense_analysis/start/ale')
	if !isdirectory(target_path)
		echo "Installing ALE..."
		silent exec "!git clone --depth 1 https://github.com/dense-analysis/ale.git"target_path
	endif
else
	echoerr "Git is required to boostrap plugins"
	execute "q!"
endif

" -------- "
" BEHAVIOR "
" -------- "
set mouse=a                       " Enable mouse support in all modes
set confirm                       " Confirm when trying to quit without saving
set clipboard=unnamedplus         " Use system clipboard
if executable('wl-copy') && executable('wl-paste')
	autocmd TextYankPost * if (v:event.operator == 'y' || v:event.operator == 'd') | silent! execute 'call system("wl-copy", @")' | endif
	nnoremap <silent> p :let @+ = system('wl-paste --no-newline')<CR>"+p
endif

if has('persistent_undo')         " Enable per-file undo history
	let target_path = expand('~/.vim/undo/')
	if !isdirectory(target_path)
		call mkdir(target_path, "p", 0700)
	endif
	let &undodir = target_path
	set undofile
endif
set backspace=indent,eol,start    " Backspace over lines/indents
set list                          " Show hidden characters
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
set splitbelow                    " Open new horizontal splits below
set splitright                    " Open new vertical splits to the right
set formatoptions+=j              " Delete comment character when joining lines
set ttimeout                      " Make ESC more responsive
set ttimeoutlen=100               " ^
set updatetime=100                " Makes async functions more responsive
let g:FYT_flash_time = 200        " Sets highlight on yank time (Miliseconds)

" ---------- "
" UI & THEME "
" ---------- "
set signcolumn=auto         " Display sign column when git signs are available
set scrolloff=20            " Always keep at least 20 lines above and below cursor
set showmode                " Show mode in modeline
set ruler                   " Show cursor position in modeline
set number                  " Show line numbers in the gutter
set relativenumber          " Show relative line numbers for jumps
set wrap                    " Wrap long lines...
set linebreak               " ...but at word boundaries...
set breakindent             " ...and while preserving indent
syntax on                   " Enable syntax highlighting
if (has("termguicolors"))
	set termguicolors
endif
set background=dark
colorscheme gruvbox8

" ------ "
" SEARCH "
" ------ "
set incsearch               " Highlight matches as you type
set hlsearch                " Keep matches highlighted
set ignorecase              " Case-insensitive search...
set smartcase               " ...unless an uppercase letter is typed
nnoremap <silent> <Esc> :nohlsearch<CR><Esc> " Clear highlighting when hitting escape

" ----------- "
" INDENTATION "
" ----------- "
set tabstop=4               " Insert 4 spaces for a tab
set shiftwidth=4            " Indent width for auto-indent and >>
set autoindent              " Copy indent from current line when starting a new one

" ---------------- "
" Completion Menus "
" ---------------- "
set complete=.,w,b,u,t,i
set completeopt=menuone,noinsert,noselect,preview
let mapleader = " "
if !exists('g:loaded_ale')
	let g:ale_completion_enabled = 1
	let g:ale_lint_on_insert_leave = 1
	let g:ale_lint_on_save = 1
	runtime! pack/ale.vim
	set omnifunc=ale#completion#OmniFunc
	let g:ale_linters = {
	\   'c': ['clang', 'clangd', 'gcc'],
	\   'python': ['pyrefly', 'ruff'],
	\   'sh': ['language_server', 'shellcheck'],
	\}
	let g:ale_fixers = {
	\   '*': ['remove_trailing_lines', 'trim_whitespace'],
	\   'c': ['clangtidy','clang-format'],
	\   'css': ['prettier'],
	\   'dockerfile': ['hadolint'],
	\   'go': ['gopls', 'gofmt'],
	\   'html': ['prettier'],
	\   'json': ['prettier'],
	\   'make': ['checkmake'],
	\   'python': ['ruff', 'ruff_format'],
	\   'sh': ['shfmt'],
	\   'yaml': ['prettier'],
	\}
	let g:ale_c_gcc_options = '-std=c99 -Wall -Wextra'
	let g:ale_c_clang_options = '-std=c99 -Wall -Wextra'
	nnoremap <leader>gd <cmd>ALEGoToDefinition<CR>
	nnoremap <leader>gi <cmd>ALEGoToImplementation<CR>
	nnoremap <leader>gr <cmd>ALEFindReferences<CR>
	nnoremap grn <Plug>(ale_rename)
	nnoremap <leader>ca <cmd>ALECodeAction<CR>
	nnoremap <leader>f <cmd>ALEFix<CR>
	nnoremap K <cmd>ALEHover<CR>
endif


set showcmd                    " Show incomplete commands in bottom bar
set wildmenu                   " Visual autocomplete for commands
set wildoptions=pum,fuzzy      " Use popup menu style, and fuzzy matching for wildmenu
set wildmode=list:longest,full " List all matches while completing the longest, then cycle
if exists('*wildtrigger')      " Automatically enable wildmenu for the command line while typing
	augroup cmdcomplete
		au!
		autocmd CmdlineChanged : call wildtrigger()
	augroup END
endif

" --------------- "
" Per File Config "
" --------------- "
filetype plugin indent on         " Enable filetype detection based behavior
augroup spellcheck
	autocmd!
	autocmd FileType markdown,text setlocal spell dictionary+=/usr/share/dict/words complete+=k
	autocmd BufNewFile,BufRead *.nf,nextflow.config set filetype=groovy
augroup END

" --------------- "
" Builtin Plugins "
" --------------- "
" Correctly highlight $() and other modern affordances in filetype=sh.
if !exists('g:is_posix') && !exists('g:is_bash') && !exists('g:is_kornshell') && !exists('g:is_dash')
	let g:is_posix = 1
endif

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
	runtime! macros/matchit.vim
endif

" Load matchparen if it hasn't been already
if !exists('g:loaded_matchparen') && findfile('plugin/matchparen.vim', &rtp) ==# ''
	runtime! plugin/matchparen.vim
endif

" Enable the :Man command shipped inside Vim's man filetype plugin.
if exists(':Man') != 2 && !exists('g:loaded_man') && &filetype !=? 'man' && !has('nvim')
	runtime! ftplugin/man.vim
endif

helptags ALL
